---
- import_playbook: ../cmn/copy_restart_sh.yml
  vars:
    restarter_snapshot_network: mainnet
- import_playbook: ../cmn/add_solv.yml
- import_playbook: ../cmn/install_package.yml
- import_playbook: ../cmn/update_ubuntu.yml
- import_playbook: install_rust.yml
- import_playbook: install_allnodes_jito.yml
- import_playbook: setup_ufw.yml
- import_playbook: fail2ban_solana_rate_limit.yml
- import_playbook: ../cmn/mount_disks.yml
- import_playbook: ../cmn/optimize_system.yml
- import_playbook: ../cmn/setup_norestart.yml
- import_playbook: configure_hugetlbfs.yml
- import_playbook: setup_logrotate.yml
- import_playbook: ../cmn/setup_unstaked_identity.yml
- import_playbook: create_overrides.yml
- import_playbook: deploy-start-validator-sh.yml
- import_playbook: setup_solv_service.yml
- import_playbook: wget_snapshot.yml
- import_playbook: start-solv-service.yml
